using System.Collections;
using System.Collections.Generic;
using UnityEngine;

// Ц育
// 1. 퀉쟕썐 name.Contain첇 player절 Destroy


/// <summary>
/// 첕쨬첔 - 첇촺쨡
/// 텈퀨 쏮 - 칭첇쮩쌰 텈퀨챹 쟶챶절 Destroy
/// </summary>
public class HealPack : MonoBehaviour
{
    [SerializeField, Tooltip("텈 쟶챶절 씱콪씶 첇퀸퀉")]
    private ParticleSystem healEffectPrefab;

    private void OnTriggerEnter(Collider other)
    {
        if(other.name.Contains("Player"))
        {
            var player = GameManager.player;
            var playerStatus = player.GetComponent<CharacterStatus>();
            playerStatus.ResetStatus();
            var playerMagic = player.GetComponent<PlayerMagic>();
            playerMagic.Reset();

            var healEffect = Instantiate(healEffectPrefab, transform.position, transform.rotation);
            gameObject.SetActive(false);
        }
    }
}